version: '3.1'

services:

  web:
    build: .
    ports:
      - "4500:5000"
    volumes:
      - ./:/app
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
